import { useState, useEffect } from 'react'
import { supabase } from '../lib/supabase'
import { useAuthStore } from '../store/authStore'

function getTodayLocal() {
    const t = new Date()
    return new Date(t.getTime() - t.getTimezoneOffset() * 60000)
        .toISOString().split('T')[0]
}

const STATUS_COLORS = {
    confirmed: 'bg-blue-50 text-blue-700',
    in_progress: 'bg-amber-50 text-amber-700',
    completed: 'bg-green-50 text-green-700',
    cancelled: 'bg-red-50 text-red-400',
    no_show: 'bg-gray-100 text-gray-400',
}

function generateDaySummary(appts, revenue, txns) {
    const cash = txns.filter(t => t.payment_mode === 'cash').reduce((s, t) => s + Number(t.total), 0)
    const upi = txns.filter(t => t.payment_mode === 'upi').reduce((s, t) => s + Number(t.total), 0)
    const card = txns.filter(t => t.payment_mode === 'card').reduce((s, t) => s + Number(t.total), 0)
    const wallet = txns.filter(t => t.payment_mode === 'wallet').reduce((s, t) => s + Number(t.total), 0)
    const done = appts.filter(a => a.status === 'completed').length
    const cancel = appts.filter(a => a.status === 'cancelled').length

    const lines = [
        'Bliss Makeover - Daily Summary',
        'Date: ' + new Date().toLocaleDateString('en-IN', {
            day: 'numeric', month: 'long', year: 'numeric'
        }),
        '',
        'Total Revenue:      Rs.' + Math.round(revenue).toLocaleString('en-IN'),
        'Total Appointments: ' + appts.length,
        'Completed: ' + done + '  |  Cancelled: ' + cancel,
        '',
        'Payment Breakdown:',
        '  Cash:   Rs.' + Math.round(cash).toLocaleString('en-IN'),
        '  UPI:    Rs.' + Math.round(upi).toLocaleString('en-IN'),
        '  Card:   Rs.' + Math.round(card).toLocaleString('en-IN'),
        '  Wallet: Rs.' + Math.round(wallet).toLocaleString('en-IN'),
        '',
        'Generated by Bliss Makeover Management System',
    ]

    const text = lines.join('\n')
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'bliss-summary-' + new Date().toISOString().split('T')[0] + '.txt'
    a.click()
    URL.revokeObjectURL(url)
}

export default function Dashboard() {
    const { profile } = useAuthStore()
    const [loading, setLoading] = useState(true)
    const [todayAppts, setTodayAppts] = useState([])
    const [todayRevenue, setTodayRevenue] = useState(0)
    const [totalCusts, setTotalCusts] = useState(0)
    const [lowStock, setLowStock] = useState([])
    const [topServices, setTopServices] = useState([])
    const [recentTxns, setRecentTxns] = useState([])
    const today = getTodayLocal()

    useEffect(() => { fetchDashboard() }, [])

    async function fetchDashboard() {
        setLoading(true)
        const [appts, revenue, custs, stock, services, txns] = await Promise.all([

            supabase.from('appointments').select(`
        id, scheduled_at, status, amount,
        customers(name, phone),
        users(name),
        services(name, duration_mins)
      `).gte('scheduled_at', today + 'T00:00:00')
                .lte('scheduled_at', today + 'T23:59:59')
                .order('scheduled_at'),

            supabase.from('transactions')
                .select('total, payment_mode')
                .gte('created_at', today + 'T00:00:00')
                .lte('created_at', today + 'T23:59:59'),

            supabase.from('customers')
                .select('id', { count: 'exact', head: true }),

            supabase.from('inventory')
                .select('id, name, stock_qty, min_level, unit')
                .order('stock_qty'),

            supabase.from('appointments')
                .select('service_id, services(name), amount')
                .eq('status', 'completed')
                .gte('scheduled_at',
                    new Date().toISOString().slice(0, 7) + '-01T00:00:00'),

            supabase.from('transactions')
                .select('total, payment_mode, created_at, customers(name), discount_amount')
                .order('created_at', { ascending: false })
                .limit(5),
        ])

        setTodayAppts(appts.data || [])

        const rev = (revenue.data || []).reduce((s, t) => s + Number(t.total), 0)
        setTodayRevenue(rev)

        setTotalCusts(custs.count || 0)

        const lowItems = (stock.data || []).filter(
            i => Number(i.stock_qty) <= Number(i.min_level)
        )
        setLowStock(lowItems)

        const svcMap = {}
            ; (services.data || []).forEach(a => {
                const name = a.services?.name || 'Unknown'
                if (!svcMap[name]) svcMap[name] = { name, count: 0, revenue: 0 }
                svcMap[name].count++
                svcMap[name].revenue += Number(a.amount || 0)
            })
        const sorted = Object.values(svcMap)
            .sort((a, b) => b.count - a.count)
            .slice(0, 5)
        const maxCount = sorted[0]?.count || 1
        setTopServices(sorted.map(s => ({
            ...s, pct: Math.round((s.count / maxCount) * 100)
        })))

        setRecentTxns(txns.data || [])
        setLoading(false)
    }

    async function updateStatus(id, status) {
        await supabase.from('appointments').update({ status }).eq('id', id)
        fetchDashboard()
    }

    const completedToday = todayAppts.filter(a => a.status === 'completed').length
    const pendingToday = todayAppts.filter(
        a => ['confirmed', 'in_progress'].includes(a.status)
    ).length

    const hour = new Date().getHours()
    const greeting = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening'

    if (loading) return (
        <div className="flex items-center justify-center h-64 text-gray-400">
            Loading dashboard...
        </div>
    )

    return (
        <div className="space-y-5">

            {/* Welcome + Day Summary */}
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-xl font-semibold text-gray-800">
                        {greeting}, {profile?.name?.split(' ')[0]}
                    </h1>
                    <p className="text-sm text-gray-400 mt-0.5">
                        {new Date().toLocaleDateString('en-IN', {
                            weekday: 'long', day: 'numeric',
                            month: 'long', year: 'numeric'
                        })}
                    </p>
                </div>
                <button
                    onClick={() => generateDaySummary(todayAppts, todayRevenue, recentTxns)}
                    className="border border-pink-200 text-pink-600 px-4 py-2 rounded-lg text-sm font-medium hover:bg-pink-50">
                    Day Summary
                </button>
            </div>

            {/* Stat cards */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className="bg-white rounded-xl border border-gray-100 p-4">
                    <div className="text-xs text-gray-400 mb-1">Today's revenue</div>
                    <div className="text-2xl font-semibold text-gray-800">
                        Rs.{todayRevenue.toLocaleString('en-IN')}
                    </div>
                    <div className="text-xs text-green-500 mt-1">
                        {completedToday} checkouts done
                    </div>
                </div>
                <div className="bg-white rounded-xl border border-gray-100 p-4">
                    <div className="text-xs text-gray-400 mb-1">Appointments today</div>
                    <div className="text-2xl font-semibold text-gray-800">
                        {todayAppts.length}
                    </div>
                    <div className="text-xs text-blue-500 mt-1">
                        {pendingToday} still pending
                    </div>
                </div>
                <div className="bg-white rounded-xl border border-gray-100 p-4">
                    <div className="text-xs text-gray-400 mb-1">Total customers</div>
                    <div className="text-2xl font-semibold text-gray-800">{totalCusts}</div>
                    <div className="text-xs text-gray-400 mt-1">in your database</div>
                </div>
                <div className="bg-white rounded-xl border border-gray-100 p-4">
                    <div className="text-xs text-gray-400 mb-1">Low stock alerts</div>
                    <div className={`text-2xl font-semibold ${lowStock.length > 0 ? 'text-amber-600' : 'text-gray-800'
                        }`}>
                        {lowStock.length}
                    </div>
                    <div className="text-xs text-amber-500 mt-1">
                        {lowStock.length > 0 ? 'items need restocking' : 'all stock levels OK'}
                    </div>
                </div>
            </div>

            {/* Birthday alerts */}
            <BirthdayAlert />

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

                {/* Today's appointments */}
                <div className="bg-white rounded-xl border border-gray-100 p-4">
                    <div className="flex items-center justify-between mb-3">
                        <h2 className="text-sm font-semibold text-gray-700">
                            Today's appointments
                        </h2>
                        <a href="/appointments"
                            className="text-xs text-pink-500 hover:text-pink-700">
                            View all
                        </a>
                    </div>
                    {todayAppts.length === 0 ? (
                        <div className="text-center text-gray-300 py-6 text-sm">
                            No appointments today
                        </div>
                    ) : (
                        <div className="space-y-2">
                            {todayAppts.slice(0, 6).map(a => (
                                <div key={a.id} className="flex items-center gap-2 text-sm">
                                    <div className="text-xs text-gray-400 w-12 flex-shrink-0 font-medium">
                                        {new Date(a.scheduled_at).toLocaleTimeString('en-IN', {
                                            hour: '2-digit', minute: '2-digit'
                                        })}
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <div className="text-gray-800 font-medium truncate text-xs">
                                            {a.customers?.name}
                                        </div>
                                        <div className="text-gray-400 truncate text-xs">
                                            {a.services?.name}
                                        </div>
                                    </div>
                                    <select
                                        value={a.status}
                                        onChange={e => updateStatus(a.id, e.target.value)}
                                        className={`text-xs px-2 py-1 rounded-full border-0 font-medium
                      focus:outline-none cursor-pointer flex-shrink-0
                      ${STATUS_COLORS[a.status]}`}>
                                        <option value="confirmed">Confirmed</option>
                                        <option value="in_progress">In Progress</option>
                                        <option value="completed">Completed</option>
                                        <option value="cancelled">Cancelled</option>
                                        <option value="no_show">No Show</option>
                                    </select>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Top services */}
                <div className="bg-white rounded-xl border border-gray-100 p-4">
                    <h2 className="text-sm font-semibold text-gray-700 mb-3">
                        Top services this month
                    </h2>
                    {topServices.length === 0 ? (
                        <div className="text-center text-gray-300 py-6 text-sm">
                            No completed services yet
                        </div>
                    ) : (
                        <div className="space-y-3">
                            {topServices.map(s => (
                                <div key={s.name}>
                                    <div className="flex justify-between text-xs mb-1">
                                        <span className="text-gray-700 font-medium truncate">
                                            {s.name}
                                        </span>
                                        <span className="text-gray-400 flex-shrink-0 ml-2">
                                            {s.count}x - Rs.{s.revenue.toLocaleString('en-IN')}
                                        </span>
                                    </div>
                                    <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden">
                                        <div
                                            className="h-full bg-pink-400 rounded-full transition-all"
                                            style={{ width: s.pct + '%' }}
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Low stock */}
                {lowStock.length > 0 && (
                    <div className="bg-white rounded-xl border border-amber-200 p-4">
                        <h2 className="text-sm font-semibold text-amber-700 mb-3">
                            Low stock - reorder needed
                        </h2>
                        <div className="space-y-2">
                            {lowStock.slice(0, 6).map(item => (
                                <div key={item.id}
                                    className="flex items-center justify-between text-xs">
                                    <span className="text-gray-700 font-medium">{item.name}</span>
                                    <span className={`font-semibold ${Number(item.stock_qty) === 0 ? 'text-red-500' : 'text-amber-600'
                                        }`}>
                                        {item.stock_qty} {item.unit} left
                                    </span>
                                </div>
                            ))}
                        </div>
                        <a href="/inventory"
                            className="mt-3 block text-center text-xs text-amber-600 font-medium hover:text-amber-800">
                            Go to inventory
                        </a>
                    </div>
                )}

                {/* Recent transactions */}
                <div className="bg-white rounded-xl border border-gray-100 p-4">
                    <h2 className="text-sm font-semibold text-gray-700 mb-3">
                        Recent payments
                    </h2>
                    {recentTxns.length === 0 ? (
                        <div className="text-center text-gray-300 py-6 text-sm">
                            No transactions yet
                        </div>
                    ) : (
                        <div className="space-y-2">
                            {recentTxns.map((t, i) => (
                                <div key={i} className="flex items-center justify-between text-xs">
                                    <div>
                                        <div className="text-gray-800 font-medium">
                                            {t.customers?.name}
                                        </div>
                                        <div className="text-gray-400">
                                            {new Date(t.created_at).toLocaleTimeString('en-IN', {
                                                hour: '2-digit', minute: '2-digit'
                                            })}
                                            {' - '}{t.payment_mode}
                                            {Number(t.discount_amount) > 0 &&
                                                ' - Rs.' + Number(t.discount_amount).toLocaleString('en-IN') + ' off'}
                                        </div>
                                    </div>
                                    <span className="font-semibold text-gray-800">
                                        Rs.{Number(t.total).toLocaleString('en-IN')}
                                    </span>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

            </div>
        </div>
    )
}

function BirthdayAlert() {
    const [birthdays, setBirthdays] = useState([])

    useEffect(() => {
        async function fetchBirthdays() {
            const today = new Date()
            const { data } = await supabase
                .from('customers')
                .select('id, name, phone, date_of_birth, loyalty_points')
                .not('date_of_birth', 'is', null)

            const upcoming = (data || []).filter(c => {
                if (!c.date_of_birth) return false
                const bday = new Date(c.date_of_birth)
                const thisYr = new Date(
                    today.getFullYear(), bday.getMonth(), bday.getDate()
                )
                const diff = Math.ceil((thisYr - today) / (1000 * 60 * 60 * 24))
                return diff >= 0 && diff <= 7
            }).map(c => {
                const bday = new Date(c.date_of_birth)
                const thisYr = new Date(
                    today.getFullYear(), bday.getMonth(), bday.getDate()
                )
                const diff = Math.ceil((thisYr - today) / (1000 * 60 * 60 * 24))
                return { ...c, daysUntil: diff }
            }).sort((a, b) => a.daysUntil - b.daysUntil)

            setBirthdays(upcoming)
        }
        fetchBirthdays()
    }, [])

    if (birthdays.length === 0) return null

    return (
        <div className="bg-pink-50 border border-pink-200 rounded-xl p-4">
            <h2 className="text-sm font-semibold text-pink-700 mb-3">
                Birthdays this week ({birthdays.length})
            </h2>
            <div className="space-y-2">
                {birthdays.map(c => (
                    <div key={c.id} className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <div className="w-7 h-7 rounded-full bg-pink-200 flex items-center
                justify-center text-pink-700 font-bold text-xs">
                                {c.name.charAt(0).toUpperCase()}
                            </div>
                            <div>
                                <div className="text-sm font-medium text-gray-800">{c.name}</div>
                                <div className="text-xs text-gray-400">{c.phone}</div>
                            </div>
                        </div>
                        <div className="text-right">
                            <div className={`text-xs font-semibold px-2 py-0.5 rounded-full ${c.daysUntil === 0
                                    ? 'bg-pink-600 text-white'
                                    : 'bg-pink-100 text-pink-700'
                                }`}>
                                {c.daysUntil === 0
                                    ? 'Today!'
                                    : 'In ' + c.daysUntil + ' day' + (c.daysUntil > 1 ? 's' : '')}
                            </div>
                            <div className="text-xs text-gray-400 mt-0.5">
                                {c.loyalty_points} pts
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    )
}